spring.application.name=PokerTracker

spring.datasource.url=jdbc:mysql://localhost:3306/PI2?useTimezone=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081