### Teste de Criação de Torneio
POST http://localhost:8080/torneios
Content-Type: application/json

{
  "descricao": "Sunday Storm",
  "plataforma": "PokerStars",
  "buyIn": 11.00,
  "rebuy": 0.0,
  "addon": 0.0,
  "itm": 0.0,
  "data": "2026-03-06"
}

### Listar todos os torneios
GET http://localhost:8080/torneios
Accept: application/json